# Generated by Django 5.2.17 on 2026-09-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booths", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booth",
            name="booth_size",
            field=models.CharField(
                blank=True,
                choices=[("SMALL", "작은 천막"), ("BIG", "큰 천막")],
                max_length=10,
                null=True,
            ),
        ),
    ]
