# Generated by Django 5.2.17 on 2026-09-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booths", "0002_booth_booth_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="boothoperation",
            name="placements",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
