# Generated by Django 5.2.17 on 2026-09-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booths", "0003_boothoperation_placements"),
    ]

    operations = [
        migrations.AddField(
            model_name="booth",
            name="restroom_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MALE", "남자 화장실"),
                    ("FEMALE", "여자 화장실"),
                    ("BOTH", "남녀 화장실"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
