# Generated by Django 6.0.5 on 2026-09-20 06:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0005_remove_boothverifycode_booth_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boothverifycode",
            name="booth",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="used_booth",
        ),
    ]
