# Generated by Django 5.2.17 on 2026-09-20 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_refreshtoken"),
        ("coupons", "0006_remove_boothverifycode_booth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupons",
                to="accounts.user",
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
